apiVersion: v1
kind: Pod
metadata:
  name: vue-starter-pod
  labels:
    app: vue-starter
spec:
  containers:
  - name: postgres
    image: docker.io/library/postgres:latest
    env:
    - name: POSTGRES_USER
      value: myuser # ✅ FIXME
    - name: POSTGRES_PASSWORD
      value: mypassword # ✅ FIXME
    - name: POSTGRES_DB
      value: mydb # ✅ FIXME
    ports:
    - containerPort: 5432
      hostPort: 5432
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: postgres-data
  volumes:
  - name: postgres-data
    hostPath:
      path: /Users/andromediano/development/podman/vue-starter/postgresql/data # ✅ FIXME
      type: Directory
