apiVersion: v1
kind: Pod
metadata:
  name: ${PROJECT_CODE}-pod
  labels:
    app: ${PROJECT_CODE}
spec:
  containers:
  - name: postgres
    image: docker.io/library/postgres:latest
    env:
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: postgres-user
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: postgres-password
    - name: POSTGRES_DB
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: postgres-db
    ports:
    - containerPort: 5432
      hostPort: 5432
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: postgres-data
  volumes:
  - name: postgres-data
    hostPath:
      path: ${POSTGRES_DATA_PATH}
      type: Directory
